logging:
  level:
    root: INFO
    com.track.training.app.customer: DEBUG
    org.apache.kafka.clients.admin: WARN

springdoc.swagger-ui.urls:
  - name: TrainTrackApp
    url: /apis/openapi.yml

management:
  endpoints.web.exposure.include: "*"

spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  sql:
    init:
      mode: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:ora
    username: c##ahidalgoo
    password: password1
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    stream:
      kafka.binder.enable-observation: true
      function:
        definition: on-customer-event;
      bindings:
        on-customer-event-out-0:
          destination: customer.events
